const DICTIONARY = {

    en: {
        MENU_TEXT: "MENU",
        START_PVP_MENU_TEXT: "1. Play PvP (Multiplayer)",
        START_PVC_MENU_TEXT: "2. Play PvC (Singleplayer)",
        SETTINGS_GAME_MENU_TEXT: "3. Settings",
        EXIT_GAME_MENU_TEXT: "4. Exit Game",
        SETTINGS_LANGUAGE_TEXT: "1. Languages",
        SETTINGS_BACK_TEXT: "2. Back",
        LANGUAGE_SETTINGS_NORWEGIAN_TEXT: "1. Norwegian",
        LANGUAGE_SETTINGS_ENGLISH_TEXT: "2. English",
        LANGUAGE_SETTINGS_BACK_TEXT: "3. Back",
        PLACE_YOUR_MARK_TEXT: "Place your mark (row column): ",
        PLAYER_TEXT: "Player ",
        YOUR_TURN_TEXT: " it is your turn",
        PLAYER_ONE_DESCRIPTION: "one",
        PLAYER_TWO_DESCRIPTION: "two",
        WINNER_IS_TEXT: "Winner is player ",
        DRAW_TEXT: "It's a draw",
        GAME_OVER_TEXT: "Game Over",
        PLAY_AGAIN_QUESTION: "Play again (YES/no)? ",
        CONFIRM: "y",
    },
    no: {
        MENU_TEXT: "MENY",
        START_PVP_MENU_TEXT: "1. Spill PvP (Flerspiller)",
        START_PVC_MENU_TEXT: "2. Spill PvC (Enkeltspiller)",
        SETTINGS_GAME_MENU_TEXT: "3. Innstillinger",
        EXIT_GAME_MENU_TEXT: "4. Avslutt spill",
        SETTINGS_LANGUAGE_TEXT: "1. Språk",
        SETTINGS_BACK_TEXT: "2. Tilbake",
        LANGUAGE_SETTINGS_NORWEGIAN_TEXT: "1. Norsk",
        LANGUAGE_SETTINGS_ENGLISH_TEXT: "2. Engelsk",
        LANGUAGE_SETTINGS_BACK_TEXT: "3. Tilbake",
        PLACE_YOUR_MARK_TEXT: "Sett et merke i en rute (rad kolonne): ",
        PLAYER_TEXT: "Spiller ",
        YOUR_TURN_TEXT: " det er din tur",
        PLAYER_ONE_DESCRIPTION: "en",
        PLAYER_TWO_DESCRIPTION: "to",
        WINNER_IS_TEXT: "Vinneren er spiller ",
        DRAW_TEXT: "Spillet endet som uavgjort",
        GAME_OVER_TEXT: "Spillet er ferdig",
        PLAY_AGAIN_QUESTION: "Spille en gang til (Ja/nei)? ",
        CONFIRM: "j",
    }
}

export default DICTIONARY;
